AWSTemplateFormatVersion: 2010-09-09
Description: Create an role with policy of run, stop and terminate instances

Resources:
  LambdaTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: stop-start-ec2-lambda-yfang
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: stop-start-ec2
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:StopInstances
                  - ec2:TerminateInstances
                Resource: "*"
